language: node_js
node_js:
  - "12"
sudo: required
services:
  - docker
before_script:
  - npm install
script:
  - docker build -t todo-api .
after_success:
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker tag todo-api $DOCKER_USER/todo-api:$TRAVIS_BUILD_NUMBER
  - docker push $DOCKER_USER/todo-api:$TRAVIS_BUILD_NUMBER
  - docker tag todo-api $DOCKER_USER/todo-api:latest
  - docker push $DOCKER_USER/todo-api:latest
